## numPy basic array

In [1]:
import numpy as np
import matplotlib.pyplot as plt

In [2]:
arr_1d = np.array([1,2,3])
arr_2d = np.array([[1,2,3],[4,5,6]])
arr_3d = np.array([[[1,2,3],[3,2,1]],[[4,5,6],[12,1,2]]])
print("1d array: \n",arr_1d)
print("\n2d array: \n",arr_2d)
print("\n3d array: \n",arr_3d)

1d array: 
 [1 2 3]

2d array: 
 [[1 2 3]
 [4 5 6]]

3d array: 
 [[[ 1  2  3]
  [ 3  2  1]]

 [[ 4  5  6]
  [12  1  2]]]


### Numpy vs Python List

In [ ]:
py_list = [1,2,3]
print("Python list multiplication: ",py_list * 2)

np_array = np.array([1,2,3])
print("Numpy array multiplication: ", np_array * 2)


Python list multiplication:  [1, 2, 3, 1, 2, 3]
Numpy array multiplication:  [2 4 6]


### Creating array from scratch

In [23]:
# np.zeros((rowa,columns))
# zeros = np.zeros((2,3))
# print(zeros)

# ones = np.ones((2,3))
# print(ones)


# full = np.full((2,3),7)
# print(full)

# arr = np.arange(10)
# print(arr)

random_matrix = np.random.random((2,3))
print(random_matrix)

[[0.77039651 0.9711512  0.88625771]
 [0.01653206 0.49930104 0.79389098]]


### Checking the diemnsion of the array 

In [ ]:
a = np.array(42)
b = np.array([1, 2, 3, 4, 5])
c = np.array([[1, 2, 3], [4, 5, 6]])
d = np.array([[[1, 2, 3], [4, 5, 6]], [[1, 2, 3], [4, 5, 6]]])

print("a array dimension: ",a.ndim)
print("b array dimension: ",b.ndim)
print("c array dimension: ",c.ndim)
print("d array dimension: ",d.ndim) 

a array dimension:  0
b array dimension:  1
c array dimension:  2
d array dimension:  3


### Vector, Matrix and tensor

In [ ]:
vector = np.array([1,2,3])
matrix = np.array([[1, 2, 3], 
                   [4, 5, 6]]) 
tensor = np.array([
    [[1, 2], [3, 4]],
    [[5, 6], [7, 8]]
])
print("Vector: \n",vector)
print("\nMatrix: \n",matrix)
print("\nTensor: \n",tensor)


Vector: 
 [1 2 3]

Matrix: 
 [[1 2 3]
 [4 5 6]]

Tensor: 
 [[[1 2]
  [3 4]]

 [[5 6]
  [7 8]]]


### Array properties

In [ ]:
arr = np.array([[1,2,3],
                [4,5,6]])
print("Shape of array: ",arr.shape)
print("Size of array: ",arr.size)
print("Dimension of arrau:" ,arr.ndim)
print("Data Type of array:", arr.dtype)

Shape of array:  (2, 3)
Size of array:  6
Dimension of arrau: 2
Data Type of array: int64


### Array Shaping

In [ ]:
arr = np.arange(12)
print("Original array: ",arr)

reshaped = arr.reshape((3,4))
print("\nReshaped array: \n",reshaped)

flattend = reshaped.flatten()
print("\n Flattend array: \n", flattend)

# ravel (returns view, insted of copy)
raveled = reshaped.ravel()
print("\n raveled array: \n", raveled)

# transpose
transpose = reshaped.T
print("\n transpose array: \n", transpose)



Original array:  [ 0  1  2  3  4  5  6  7  8  9 10 11]

Reshaped array: 
 [[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]]

 Flattend array: 
 [ 0  1  2  3  4  5  6  7  8  9 10 11]

 raveled array: 
 [ 0  1  2  3  4  5  6  7  8  9 10 11]

 transpose array: 
 [[ 0  4  8]
 [ 1  5  9]
 [ 2  6 10]
 [ 3  7 11]]


### Indexing and Slicing

In [ ]:
arr = np.array([1,2,3,4,5,6,7,8,8,10])
print(arr[1:7])
print(arr[1:7:2])
print(arr[2])

[2 3 4 5 6 7]
[2 4 6]
3


In [ ]:
arr_2d = np.array([[1,2,3],
                   [4,5,6],
                   [7,8,9]])
print("Specific element",arr_2d[1,1])
print("Entire row: ", arr_2d[1])
print("Entrie Column: ",arr_2d[:,1])

Specific element 5
Entire row:  [4 5 6]
Entrie Column:  [2 5 8]


### Sorting

In [3]:
arr_1d = np.array([4,1,6,2,8,9,3])
print("Sorted Array: ", np.sort(arr_1d))

Sorted Array:  [1 2 3 4 6 8 9]


In [5]:
arr_2d = np.array([[3,1],[9,3],[8,2]])
print(np.sort(arr_2d))
print("Sorted 2d array by column",np.sort(arr_2d, axis=0))
print("Sorted 2d array by rows", np.sort(arr_2d, axis=1))

[[1 3]
 [3 9]
 [2 8]]
Sorted 2d array by column [[3 1]
 [8 2]
 [9 3]]
Sorted 2d array by rows [[1 3]
 [3 9]
 [2 8]]


### Filter

In [ ]:
numbers = np.array([1,2,3,4,5,6,7,8,9,10])
even_number = numbers[numbers%2 == 0]
print(even_number)

[ 2  4  6  8 10]


### Filter with Mask

In [10]:
mask = numbers > 5
print("only mask vairable print:",mask)
print("Number greater than 5: ", numbers[mask])

only mask vairable print: [False False False False False  True  True  True  True  True]
Number greater than 5:  [ 6  7  8  9 10]


### Indexing vs np.where()

In [22]:
# numbers = np.array([1,2,3,4,5,6,7,8,9,10])
# indices = [1,4,7]
# print(numbers[indices])

Where_result = np.where(numbers > 5)
print("Only Where result: ", Where_result)
print("Numbers where result: ", numbers[Where_result])


Only Where result:  (array([5, 6, 7, 8, 9]),)
Numbers where result:  [ 6  7  8  9 10]


In [24]:
numbers = np.array([1,2,3,4,5,6,7,8,9,10])
condition_array = np.where(numbers > 5, numbers*4, numbers)
print(condition_array)

[ 1  2  3  4  5 24 28 32 36 40]


### Adding and removing data

In [30]:
arr1 = np.array([1,2,3,4])
arr2 = np.array([5,6,7,8])
arr3 = np.array([9,10,11,12])
adding = arr1+arr2+arr3
combined = np.concatenate((arr1, arr2, arr3))
print("This is do addition between arrays: ",adding)
print("Meging between array: ",combined)

This is do addition between arrays:  [15 18 21 24]
Meging between array:  [ 1  2  3  4  5  6  7  8  9 10 11 12]


### Row merge in n dimension and column merge in n diemsntion 

In [36]:
arr1 = np.array([[1,2],[3,4]])
new_row = np.array([[5,6]])
with_new_row = np.vstack((arr1,new_row))
print(with_new_row)

new_col = np.array([[1],[2]])
with_col = np.hstack((arr1,new_col))
print(with_col)

[[1 2]
 [3 4]
 [5 6]]
[[1 2 1]
 [3 4 2]]


### Delete

In [38]:
arr = np.array([1,2,3,4,5,6,7,8])
new_array = np.delete(arr,2)
print(new_array)

[1 2 4 5 6 7 8]


In [ ]:
matrix = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9]])
new_matrix = np.delete(matrix, 1, axis=0)  # Deletes row at index 1
print(new_matrix)


[[1 2 3]
 [7 8 9]]


In [40]:
matrix = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9]])
new_matrix = np.delete(matrix, 1, axis=1)  # Deletes column at index 1
print(new_matrix)


[[1 3]
 [4 6]
 [7 9]]


In [42]:
arr = np.array([10, 20, 30, 40, 50])
new_arr = np.delete(arr, [1, 3])
print(new_arr)


[10 30 50]


### Advance operations with Business examples

In [49]:
# Data structure: [restaurant_id, 2021, 2022, 2023, 2024]

sales_data = np.array([
    [1,150000,180000,220000,250000],
    [2,120000,140000,160000,190000],
    [3,200000,230000,260000,300000],
    [4,180000,210000,240000,270000],
    [5,160000,210000,205000,230000]
])
print("=== Data analysis ===")
print("\n Sales data shape",sales_data.shape)
print("\n Sample data of 1st 3 resturant: \n", sales_data[:3])

=== Data analysis ===

 Sales data shape (5, 5)

 Sample data of 1st 3 resturant: 
 [[     1 150000 180000 220000 250000]
 [     2 120000 140000 160000 190000]
 [     3 200000 230000 260000 300000]]


In [64]:
year_total = np.sum(sales_data[:, 1:],axis=0)
print(year_total)

min_sales = np.min(sales_data[:,1:], axis=1)
print(sales_data[:, 0:2:3])
print(min_sales)

[ 810000  970000 1085000 1240000]
[[1]
 [2]
 [3]
 [4]
 [5]]
[150000 120000 200000 180000 160000]


In [ ]:
vector1 = np.array([1,2,3,4,5])
vector2 = np.array([6,7,8,9,10])

print("Vector Addition: ", vector1+vector2)
print("Multiplication vector: ", vector1 * vector2)
print("Dot product: ",np.dot(vector1,vector2))

angle = np.arccos(np.dot(vector1,vector2) / (np.linalg.norm(vector1) * np.linalg.norm(vector2)))
print(angle)

0.26554161733900966


In [71]:
restaurant_type = np.array(["chiness","biryani","pizza"])
vectorized_upper = np.vectorize(str.upper)
print(vectorized_upper(restaurant_type))

['CHINESS' 'BIRYANI' 'PIZZA']


In [73]:
sales_data = np.array([
    [1,150000,180000,220000,250000],
    [2,120000,140000,160000,190000],
    [3,200000,230000,260000,300000],
    [4,180000,210000,240000,270000],
    [5,160000,210000,205000,230000]
])

month_avg = sales_data[:,1:] / 12
print(month_avg)

[[12500.         15000.         18333.33333333 20833.33333333]
 [10000.         11666.66666667 13333.33333333 15833.33333333]
 [16666.66666667 19166.66666667 21666.66666667 25000.        ]
 [15000.         17500.         20000.         22500.        ]
 [13333.33333333 17500.         17083.33333333 19166.66666667]]


In [76]:
arr1 = np.array([[1,2,3],[2,4,1]])
np.save("array1.npy",arr1)
print(arr1)

[[1 2 3]
 [2 4 1]]


In [77]:
loaded_array = np.load("array1.npy")
print(loaded_array)

[[1 2 3]
 [2 4 1]]
